CREATE TABLE Users (id TEXT PRIMARY KEY, name TEXT, hash TEXT, email TEXT, address TEXT);
INSERT INTO Users (id, name, hash, email, adress) VALUES
    ("4dea5a94-92b1-41e9-8fa4-f7a69680fbb3", "user1", "$2b$10$57TmZMb3R3S8ArtA9y2XZeX0s/hIer0qmlljvCVlfn7kIQ1zHvWD.", "user1@example.com", "123 Main St."),
    ("5a3b749a-fd1d-499d-9709-3189df034c0e", "user2", "$2b$10$kvoM2g1kWSCdwaBBYPaPWO4a2AaIl/i1O3eixWP9nupf4ZX3LT77.", "user2@example.com", "456 Elm St."),
    ("7296bc11-0676-4b64-b042-044a3a9a801b", "user3", "$2b$10$P3vwlj95uvEKyPGeBI0puOEci3WJOYs62nT7TsEnmvShyXUAW6Guy", "user3@example.com", "789 Oak St."),
    ("10892d71-ba36-4a72-88f6-915fb6e8b6e0", "user4", "$2b$10$FqkitUiL609MEhfPIv934ebKrwdBKzzWKHkTnEH8if2WhwrfEtgfy", "user4@example.com", "1011 Pine St."),
    ("9fb05aaf-1b02-4c9b-8395-28b2f95410ac", "user5", "$2b$10$53fyieag2/CwXRUCbJ6waeHC5f/O6r1Oo2CP07fo3CZ.myQA8my32", "user5@example.com", "1213 Cedar St.");

CREATE TABLE Sessions (id INTEGER PRIMARY KEY, user_id INTEGER, token TEXT);

CREATE TABLE Authors (
    AuthorID INTEGER PRIMARY KEY AUTOINCREMENT,
    Name TEXT NOT NULL,
    BirthYear INTEGER,
    ImageURL TEXT,
    WikipediaURL TEXT
);

CREATE TABLE Publishers (
    PublisherID INTEGER PRIMARY KEY AUTOINCREMENT,
    Name TEXT NOT NULL,
    WikipediaURL TEXT
);

CREATE TABLE Books (
    BookID INTEGER PRIMARY KEY AUTOINCREMENT,
    Title TEXT NOT NULL,
    Genre TEXT,
    Year INTEGER,
    PublisherID INTEGER,
    CoverImageURL TEXT,
    Description TEXT,
    FOREIGN KEY (PublisherID) REFERENCES Publishers(PublisherID)
);

CREATE TABLE AuthorBooks (
    AuthorID INTEGER,
    BookID INTEGER,
    PRIMARY KEY (AuthorID, BookID),
    FOREIGN KEY (AuthorID) REFERENCES Authors(AuthorID),
    FOREIGN KEY (BookID) REFERENCES Books(BookID)
);

-- Insert statements for Authors table
INSERT INTO Authors (Name, BirthYear, ImageURL, WikipediaURL) VALUES
('Harper Lee', 1926, 'harperlee.jpg', 'https://en.wikipedia.org/wiki/Harper_Lee'),
('George Orwell', 1903, 'georgeorwell.jpg', 'https://en.wikipedia.org/wiki/George_Orwell'),
('F. Scott Fitzgerald', 1896, 'fscottfitzgerald.jpg', 'https://en.wikipedia.org/wiki/F._Scott_Fitzgerald'),
('Jane Austen', 1775, 'janeausten.jpg', 'https://en.wikipedia.org/wiki/Jane_Austen'),
('J. D. Salinger', 1919, 'jdsalinger.jpg', 'https://en.wikipedia.org/wiki/J._D._Salinger'),
('William Golding', 1911, 'williamgolding.jpg', 'https://en.wikipedia.org/wiki/William_Golding'),
('J.R.R. Tolkien', 1892, 'tolkien.jpg', 'https://en.wikipedia.org/wiki/J._R._R._Tolkien'),
('Aldous Huxley', 1894, 'aldoushuxley.jpg', 'https://en.wikipedia.org/wiki/Aldous_Huxley'),
('Charlotte Brontë', 1816, 'charlottebronte.jpg', 'https://en.wikipedia.org/wiki/Charlotte_Bront%C3%AB'),
('Herman Melville', 1819, 'hermanmelville.jpg', 'https://en.wikipedia.org/wiki/Herman_Melville'),
('Mary Shelley', 1797, 'maryshelley.jpg', 'https://en.wikipedia.org/wiki/Mary_Shelley'),
('Emily Brontë', 1818, 'emilybronte.jpg', 'https://en.wikipedia.org/wiki/Emily_Bront%C3%AB'),
('Oscar Wilde', 1854, 'oscarwilde.jpg', 'https://en.wikipedia.org/wiki/Oscar_Wilde'),
('Fyodor Dostoevsky', 1821, 'fyodordostoevsky.jpg', 'https://en.wikipedia.org/wiki/Fyodor_Dostoevsky'),
('Gabriel García Márquez', 1927, 'gabrielgarciamarquez.jpg', 'https://en.wikipedia.org/wiki/Gabriel_Garc%C3%ADa_M%C3%A1rquez'),
('Leo Tolstoy', 1828, 'leotolstoy.jpg', 'https://en.wikipedia.org/wiki/Leo_Tolstoy'),
('Alexandre Dumas', 1802, 'alexandredumas.jpg', 'https://en.wikipedia.org/wiki/Alexandre_Dumas'),
('Nathaniel Hawthorne', 1804, 'nathanielhawthorne.jpg', 'https://en.wikipedia.org/wiki/Nathaniel_Hawthorne'),
('Jonathan Swift', 1667, 'jonathanswift.jpg', 'https://en.wikipedia.org/wiki/Jonathan_Swift'),
('Dante Alighieri', 1265, 'dantealighieri.jpg', 'https://en.wikipedia.org/wiki/Dante_Alighieri'),
('Geoffrey Chaucer', 1343, 'geoffreychaucer.jpg', 'https://en.wikipedia.org/wiki/Geoffrey_Chaucer'),
('Homer', -800, 'homer.jpg', 'https://en.wikipedia.org/wiki/Homer'),
('Virgil', -70, 'virgil.jpg', 'https://en.wikipedia.org/wiki/Virgil'),
('Mark Twain', 1835, 'marktwain.jpg', 'https://en.wikipedia.org/wiki/Mark_Twain'),
('Henry David Thoreau', 1817, 'henrydavidthoreau.jpg', 'https://en.wikipedia.org/wiki/Henry_David_Thoreau'),
('Victor Hugo', 1802, 'victorhugo.jpg', 'https://en.wikipedia.org/wiki/Victor_Hugo'),
('Charles Dickens', 1812, 'charlesdickens.jpg', 'https://en.wikipedia.org/wiki/Charles_Dickens'),
('Daniel Defoe', 1660, 'danieldefoe.jpg', 'https://en.wikipedia.org/wiki/Daniel_Defoe'),
('A. A. Milne', 1882, 'aamilne.jpg', 'https://en.wikipedia.org/wiki/A._A._Milne'),
('Kenneth Grahame', 1859, 'kennethgrahame.jpg', 'https://en.wikipedia.org/wiki/Kenneth_Grahame'),
('Frances Hodgson Burnett', 1849, 'franceshodgsonburnett.jpg', 'https://en.wikipedia.org/wiki/Frances_Hodgson_Burnett'),
('Edgar Rice Burroughs', 1875, 'edgarriceburroughs.jpg', 'https://en.wikipedia.org/wiki/Edgar_Rice_Burroughs'),
('Lewis Carroll', 1832, 'lewiscarroll.jpg', 'https://en.wikipedia.org/wiki/Lewis_Carroll'),
('Michael Crichton', 1942, 'michaelcrichton.jpg', 'https://en.wikipedia.org/wiki/Michael_Crichton'),
('Suzanne Collins', 1962, 'suzannecollins.jpg', 'https://en.wikipedia.org/wiki/Suzanne_Collins'),
('Dan Brown', 1964, 'danbrown.jpg', 'https://en.wikipedia.org/wiki/Dan_Brown'),
('Stephenie Meyer', 1973, 'stepheniemeyer.jpg', 'https://en.wikipedia.org/wiki/Stephenie_Meyer'),
('J.K. Rowling', 1965, 'jkrowling.jpg', 'https://en.wikipedia.org/wiki/J._K._Rowling'),
('Stieg Larsson', 1954, 'stieglarsson.jpg', 'https://en.wikipedia.org/wiki/Stieg_Larsson'),
('Paulo Coelho', 1947, 'paulocoelho.jpg', 'https://en.wikipedia.org/wiki/Paulo_Coelho'),
('Stephen King', 1947, 'stephenking.jpg', 'https://en.wikipedia.org/wiki/Stephen_King');

-- Insert statements for Publishers table
INSERT INTO Publishers (Name, WikipediaURL) VALUES
('HarperCollins', 'https://en.wikipedia.org/wiki/HarperCollins'),
('Secker & Warburg', 'https://en.wikipedia.org/wiki/Secker_%26_Warburg'),
('Scribner', 'https://en.wikipedia.org/wiki/Charles_Scribner%27s_Sons'),
('Thomas Egerton', 'https://en.wikipedia.org/wiki/Thomas_Egerton_(publisher)'),
('J. B. Lippincott & Co.', 'https://en.wikipedia.org/wiki/J._B._Lippincott_%26_Co.'),
('Faber and Faber', 'https://en.wikipedia.org/wiki/Faber_and_Faber'),
('Allen & Unwin', 'https://en.wikipedia.org/wiki/Allen_%26_Unwin'),
('Chatto & Windus', 'https://en.wikipedia.org/wiki/Chatto_%26_Windus'),
('Richard Bentley', 'https://en.wikipedia.org/wiki/Richard_Bentley_(publisher)'),
('Penguin Classics', 'https://en.wikipedia.org/wiki/Penguin_Classics'),
('W. W. Norton & Company', 'https://en.wikipedia.org/wiki/W._W._Norton_%26_Company'),
('Viking Press', 'https://en.wikipedia.org/wiki/Viking_Press'),
('D. Appleton & Company', 'https://en.wikipedia.org/wiki/D._Appleton_%26_Company'),
('Random House', 'https://en.wikipedia.org/wiki/Random_House'),
('Doubleday', 'https://en.wikipedia.org/wiki/Doubleday_(publisher)'),
('Houghton Mifflin', 'https://en.wikipedia.org/wiki/Houghton_Mifflin_Harcourt'),
('Chapman & Hall', 'https://en.wikipedia.org/wiki/Chapman_%26_Hall'),
('W. W. Norton & Company', 'https://en.wikipedia.org/wiki/W._W._Norton_%26_Company'),
('George Routledge & Sons', 'https://en.wikipedia.org/wiki/George_Routledge_%26_Sons'),
('Oxford University Press', 'https://en.wikipedia.org/wiki/Oxford_University_Press'),
('Jonathan Cape', 'https://en.wikipedia.org/wiki/Jonathan_Cape'),
('Cassell & Co', 'https://en.wikipedia.org/wiki/Cassell_%26_Co'),
('Modern Library', 'https://en.wikipedia.org/wiki/Modern_Library'),
('Puffin Books', 'https://en.wikipedia.org/wiki/Puffin_Books'),
('Methuen Publishing', 'https://en.wikipedia.org/wiki/Methuen_Publishing'),
('Grosset & Dunlap', 'https://en.wikipedia.org/wiki/Grosset_%26_Dunlap'),
('Macmillan Publishers', 'https://en.wikipedia.org/wiki/Macmillan_Publishers'),
('Henry Holt and Company', 'https://en.wikipedia.org/wiki/Henry_Holt_and_Company'),
('Dover Publications', 'https://en.wikipedia.org/wiki/Dover_Publications'),
('Little, Brown and Company', 'https://en.wikipedia.org/wiki/Little,_Brown_and_Company'),
('Walker Books', 'https://en.wikipedia.org/wiki/Walker_Books'),
('Candlewick Press', 'https://en.wikipedia.org/wiki/Candlewick_Press'),
('Scholastic Corporation', 'https://en.wikipedia.org/wiki/Scholastic_Corporation'),
('Anchor Books', 'https://en.wikipedia.org/wiki/Anchor_Books'),
('Alfred A. Knopf', 'https://en.wikipedia.org/wiki/Alfred_A._Knopf'),
('Bloomsbury Publishing', 'https://en.wikipedia.org/wiki/Bloomsbury_Publishing'),
('Penguin Books', 'https://en.wikipedia.org/wiki/Penguin_Books'),
('Random House', 'https://en.wikipedia.org/wiki/Random_House'),
('Little, Brown and Company', 'https://en.wikipedia.org/wiki/Little,_Brown_and_Company'),
('Vintage Books', 'https://en.wikipedia.org/wiki/Vintage_Books'),
('Atom Books', 'https://en.wikipedia.org/wiki/Atom_Books'),
('Arthur A. Levine Books', 'https://en.wikipedia.org/wiki/Arthur_A._Levine_Books'),
('Quercus', 'https://en.wikipedia.org/wiki/Quercus_(publisher)'),
('Doubleday', 'https://en.wikipedia.org/wiki/Doubleday_(publisher)'),
('Riverhead Books', 'https://en.wikipedia.org/wiki/Riverhead_Books'),
('St. Martin''s Press', 'https://en.wikipedia.org/wiki/St._Martin%27s_Press'),
('Knopf Doubleday Publishing Group', 'https://en.wikipedia.org/wiki/Knopf_Doubleday_Publishing_Group');


INSERT INTO Books (Title, Genre, Year, PublisherID, CoverImageURL, Description) VALUES
('To Kill a Mockingbird', 'Fiction', 1960, 1, 'mockingbird.jpg', 'A classic novel by Harper Lee.'),
('1984', 'Dystopian', 1949, 2, '1984.jpg', 'A dystopian novel by George Orwell.'),
('The Great Gatsby', 'Fiction', 1925, 3, 'gatsby.jpg', 'A novel by F. Scott Fitzgerald.'),
('Pride and Prejudice', 'Romance', 1813, 4, 'pride.jpg', 'A romantic novel by Jane Austen.'),
('The Catcher in the Rye', 'Fiction', 1951, 5, 'catcher.jpg', 'A novel by J. D. Salinger.'),
('Animal Farm', 'Political satire', 1945, 2, 'animalfarm.jpg', 'A satirical novella by George Orwell.'),
('Lord of the Flies', 'Fiction', 1954, 6, 'lord.jpg', 'A novel by William Golding.'),
('The Hobbit', 'Fantasy', 1937, 7, 'hobbit.jpg', 'A fantasy novel by J.R.R. Tolkien.'),
('Brave New World', 'Dystopian', 1932, 8, 'bravenewworld.jpg', 'A dystopian novel by Aldous Huxley.'),
('Jane Eyre', 'Gothic fiction', 1847, 9, 'janeeyre.jpg', 'A novel by Charlotte Brontë.'),
('Moby-Dick', 'Adventure', 1851, 10, 'mobydick.jpg', 'A novel by Herman Melville.'),
('The Lord of the Rings', 'Fantasy', 1954, 7, 'lotr.jpg', 'A fantasy epic by J.R.R. Tolkien.'),
('Frankenstein', 'Gothic fiction', 1818, 11, 'frankenstein.jpg', 'A novel by Mary Shelley.'),
('Wuthering Heights', 'Gothic fiction', 1847, 9, 'wutheringheights.jpg', 'A novel by Emily Brontë.'),
('The Picture of Dorian Gray', 'Gothic fiction', 1890, 12, 'doriangray.jpg', 'A novel by Oscar Wilde.'),
('Crime and Punishment', 'Psychological fiction', 1866, 13, 'crime.jpg', 'A novel by Fyodor Dostoevsky.'),
('One Hundred Years of Solitude', 'Magic realism', 1967, 14, 'solitude.jpg', 'A novel by Gabriel García Márquez.'),
('The Brothers Karamazov', 'Philosophical fiction', 1880, 13, 'brothersk.jpg', 'A novel by Fyodor Dostoevsky.'),
('The Grapes of Wrath', 'Realistic fiction', 1939, 15, 'grapes.jpg', 'A novel by John Steinbeck.'),
('The Odyssey', 'Epic poetry', -800, 16, 'odyssey.jpg', 'An epic poem attributed to Homer.'),
('Anna Karenina', 'Realistic fiction', 1877, 17, 'anna.jpg', 'A novel by Leo Tolstoy.'),
('The Count of Monte Cristo', 'Adventure', 1844, 18, 'monte.jpg', 'A novel by Alexandre Dumas.'),
('The Scarlet Letter', 'Historical fiction', 1850, 19, 'scarlet.jpg', 'A novel by Nathaniel Hawthorne.'),
('Gulliver''s Travels', 'Satire', 1726, 20, 'gulliver.jpg', 'A novel by Jonathan Swift.'),
('The Divine Comedy', 'Epic poetry', 1320, 21, 'divine.jpg', 'An epic poem by Dante Alighieri.'),
('The Canterbury Tales', 'Verse', 1400, 22, 'canterbury.jpg', 'A collection of stories by Geoffrey Chaucer.'),
('The Iliad', 'Epic poetry', -800, 16, 'iliad.jpg', 'An epic poem attributed to Homer.'),
('The Aeneid', 'Epic poetry', -19, 23, 'aeneid.jpg', 'An epic poem by Virgil.'),
('The Adventures of Tom Sawyer', 'Adventure', 1876, 24, 'tomsawyer.jpg', 'A novel by Mark Twain.'),
('The Three Musketeers', 'Adventure', 1844, 25, 'musketeers.jpg', 'A novel by Alexandre Dumas.'),
('Walden', 'Autobiography', 1854, 26, 'walden.jpg', 'A book by Henry David Thoreau.'),
('Les Misérables', 'Historical fiction', 1862, 27, 'lesmis.jpg', 'A novel by Victor Hugo.'),
('Great Expectations', 'Realistic fiction', 1861, 28, 'expectations.jpg', 'A novel by Charles Dickens.'),
('David Copperfield', 'Realistic fiction', 1850, 28, 'copperfield.jpg', 'A novel by Charles Dickens.'),
('Oliver Twist', 'Realistic fiction', 1837, 28, 'oliver.jpg', 'A novel by Charles Dickens.'),
('Robinson Crusoe', 'Adventure', 1719, 29, 'crusoe.jpg', 'A novel by Daniel Defoe.'),
('Winnie-the-Pooh', 'Children''s literature', 1926, 30, 'winnie.jpg', 'A children''s book by A. A. Milne.'),
('The Wind in the Willows', 'Children''s literature', 1908, 31, 'wind.jpg', 'A children''s book by Kenneth Grahame.'),
('A Tale of Two Cities', 'Historical fiction', 1859, 28, 'tale.jpg', 'A novel by Charles Dickens.'),
('A Christmas Carol', 'Novella', 1843, 28, 'christmas.jpg', 'A novella by Charles Dickens.'),
('War and Peace', 'Historical fiction', 1869, 17, 'warpeace.jpg', 'A novel by Leo Tolstoy.'),
('The Adventures of Huckleberry Finn', 'Adventure', 1884, 24, 'huckleberry.jpg', 'A novel by Mark Twain.'),
('Don Quixote', 'Picaresque', 1605, 32, 'donquixote.jpg', 'A novel by Miguel de Cervantes.'),
('Sense and Sensibility', 'Romance', 1811, 33, 'sense.jpg', 'A romantic novel by Jane Austen.'),
('Heart of Darkness', 'Adventure', 1899, 34, 'heart.jpg', 'A novella by Joseph Conrad.'),
('Gone with the Wind', 'Historical fiction', 1936, 35, 'gone.jpg', 'A novel by Margaret Mitchell.'),
('The Adventures of Sherlock Holmes', 'Mystery', 1892, 36, 'sherlock.jpg', 'A collection of stories by Arthur Conan Doyle.'),
('The Call of the Wild', 'Adventure', 1903, 37, 'call.jpg', 'A novel by Jack London.'),
('The War of the Worlds', 'Science fiction', 1898, 38, 'warworlds.jpg', 'A novel by H. G. Wells.'),
('Dracula', 'Gothic fiction', 1897, 39, 'dracula.jpg', 'A novel by Bram Stoker.'),
('Around the World in Eighty Days', 'Adventure', 1873, 40, 'around.jpg', 'A novel by Jules Verne.'),
('The Secret Garden', 'Children''s literature', 1911, 41, 'secretgarden.jpg', 'A children''s novel by Frances Hodgson Burnett.'),
('Tarzan of the Apes', 'Adventure', 1912, 42, 'tarzan.jpg', 'A novel by Edgar Rice Burroughs.'),
('Alice''s Adventures in Wonderland', 'Fantasy', 1865, 43, 'alice.jpg', 'A novel by Lewis Carroll.'),
('The Time Machine', 'Science fiction', 1895, 38, 'timemachine.jpg', 'A novel by H. G. Wells.'),
('Jurassic Park', 'Science fiction', 1990, 44, 'jurassic.jpg', 'A novel by Michael Crichton.'),
('The Hunger Games', 'Science fiction', 2008, 45, 'hungergames.jpg', 'A novel by Suzanne Collins.'),
('The Da Vinci Code', 'Mystery', 2003, 46, 'davinci.jpg', 'A novel by Dan Brown.'),
('Twilight', 'Romance', 2005, 47, 'twilight.jpg', 'A novel by Stephenie Meyer.'),
('Harry Potter and the Philosopher''s Stone', 'Fantasy', 1997, 48, 'harry.jpg', 'A fantasy novel by J.K. Rowling.'),
('The Girl with the Dragon Tattoo', 'Mystery', 2005, 49, 'dragon.jpg', 'A novel by Stieg Larsson.'),
('The Alchemist', 'Adventure', 1988, 50, 'alchemist.jpg', 'A novel by Paulo Coelho.'),
('The Shining', 'Horror', 1977, 51, 'shining.jpg', 'A novel by Stephen King.'),
('The Catcher in the Rye', 'Fiction', 1951, 52, 'catcher2.jpg', 'A novel by J. D. Salinger.');


-- Insert statements for AuthorBooks table
INSERT INTO AuthorBooks (AuthorID, BookID) VALUES
(1, 1),
(2, 2),
(3, 3),
(4, 4),
(5, 5),
(6, 6),
(7, 7),
(8, 8),
(9, 9),
(10, 10),
(11, 11),
(12, 12),
(13, 13),
(14, 14),
(15, 15),
(16, 16),
(17, 17),
(18, 18),
(19, 19),
(20, 20),
(21, 21),
(22, 22),
(23, 23),
(24, 24),
(25, 25),
(26, 26),
(27, 27),
(28, 28),
(28, 29),
(28, 30),
(28, 31),
(28, 32),
(28, 33),
(28, 34),
(28, 35),
(28, 36),
(28, 37),
(28, 38),
(28, 39),
(28, 40),
(28, 41),
(28, 42),
(28, 43),
(28, 44),
(28, 45),
(28, 46),
(28, 47),
(28, 48),
(28, 49),
(28, 50),
(28, 51),
(5, 52); -- Repeating for illustration purposes, assuming J.D. Salinger wrote "The Catcher in the Rye" twice.
